// EU country config: tax ID labels, VAT rates, currency, flag emoji
export const EU_COUNTRIES = [
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    taxIdLabel: "NIF / CIF",
    taxIdPlaceholder: "B12345678",
    vatRates: [0, 4, 10, 21],
    defaultVat: 21,
    currency: "EUR",
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    taxIdLabel: "Steuernummer",
    taxIdPlaceholder: "12/345/67890",
    vatRates: [0, 7, 19],
    defaultVat: 19,
    currency: "EUR",
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    taxIdLabel: "SIRET / SIREN",
    taxIdPlaceholder: "12345678901234",
    vatRates: [0, 2.1, 5.5, 10, 20],
    defaultVat: 20,
    currency: "EUR",
  },
  {
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    taxIdLabel: "Partita IVA",
    taxIdPlaceholder: "IT12345678901",
    vatRates: [0, 4, 5, 10, 22],
    defaultVat: 22,
    currency: "EUR",
  },
  {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    taxIdLabel: "BTW-nummer",
    taxIdPlaceholder: "NL123456789B01",
    vatRates: [0, 9, 21],
    defaultVat: 21,
    currency: "EUR",
  },
  {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    taxIdLabel: "NIP",
    taxIdPlaceholder: "1234567890",
    vatRates: [0, 5, 8, 23],
    defaultVat: 23,
    currency: "PLN",
  },
  {
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    taxIdLabel: "VAT Number",
    taxIdPlaceholder: "IE1234567T",
    vatRates: [0, 9, 13.5, 23],
    defaultVat: 23,
    currency: "EUR",
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    taxIdLabel: "NIF",
    taxIdPlaceholder: "123456789",
    vatRates: [0, 6, 13, 23],
    defaultVat: 23,
    currency: "EUR",
  },
  {
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    taxIdLabel: "BTW / TVA",
    taxIdPlaceholder: "BE0123456789",
    vatRates: [0, 6, 12, 21],
    defaultVat: 21,
    currency: "EUR",
  },
  {
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    taxIdLabel: "UID-Nummer",
    taxIdPlaceholder: "ATU12345678",
    vatRates: [0, 10, 13, 20],
    defaultVat: 20,
    currency: "EUR",
  },
]

export function getCountryByCode(code: string) {
  return EU_COUNTRIES.find((c) => c.code === code)
}
